### ISSUE TITLE
Ship Armor

### ISSUE THREAD

**Issue by trainb0y** [Stellarica/Stellarica#102]

**Comment by HyperSoop** [comment]
Reposting from/summing up https://github.com/Stellarica/Stellarica-Server/issues/6

Ship armor and shields absorb damage to blocks in a radius around them, be that explosive or otherwise.
> Basically, when a block gets broken and there is an armor block within acceptable radius of it the block doesn't break and the armor gets damaged by a value calculated from the block's blast resistance.

 They have their own durability, and when armor hits 0% durability, the block itself breaks; when shields hit 0% charge, they stop working. Armor has a 1 block radius with near 100% damage reduction, shields have a large radius, but lower damage reduction, the scaling of which is explained below.
 The damage reduction percentage basically multiplies the blast resistance of blocks around it. 95% would make the blocks 20 times more resistant, 50% would make them 2 times as hard to break, 20% would be 1.25 times the strength. `100/(100-x)`

The shield progression would be to build up more of its multiblock for more radius (& some passive energy spend for higher radiuses as a permanent downside keeping smaller shields viable for small areas in the endgame) and to pump more energy into it for more defence. The way the energy part would work is that when a shield'd be above 50% in charge, it'd recieve a boost to its efficency (only works with multiblock shields), the more energy, the bigger, in an exponential way. That is, if 50% charge is 30% protection, 60% charge would be 35%, 70%-45% 80%-60% 90%- 80%, 100%-100%, so the more energy you have to pump into the shield, the more protection you get on average if you're being constantly attacked. That is, it both follows the premise of making the first few hits on your ship easily resistable, AND the idea of letting ground bases be very hard to raid! (since such bases would be self-sustainable in terms of energy, and be able to produce much more than size-limited ships. _We should also add thermal energy generators to reinforce this_)  

For armor, it's easy. They take priority below shields in reflecting damage, and their progression consists of using different crafting recipes to get armor of different durability (with each type reflecting pretty much all damage no matter the durability, and breaking when the durability is done)

![a](https://user-images.githubusercontent.com/85982640/217006491-1cbf9493-51c5-4f31-b386-62bbf8b1ee90.png)

> armor blocks could be based off vanilla respawn anchors, they have a charge display which is exactly what we need to indicate armor block durability

**Comment by HyperSoop** [comment]
After some consideration, here's some changes to how armor should work:
Instead of working in a radius, it would instead cover an amount of non-air blocks around it, with its area of effect "spreading" from block to block. That would help to reduce the burden of placing armor all around the ship, as fewer would be needed and they'd automatically be pretty efficent no matter the specific placement. Armor should also not prevent block breaking by players in its area of effect, instead leaving it to shields (for obvious reasons, so as not to be annoying if you wanna rebuild or expand upon your ship), it would still serve its purpose against explosions and other weapons though.

Shields would prevent block breaking and block placement (placed blocks would break a few seconds after being placed) in their radius of effect, and they would need a "keycard" system in order to make it posible for base/ship owners to build and break stuff. Every shield would have an option to set a "password" to it in its interface, which would allow players with the same password stored in their inventories to bypass the effects of the matching shield. The passwords could be stored in a sort of "electromagnetic keychain" item, being a writable book where each new line is considered a new shield password.

**Comment by HyperSoop** [comment]
this is hell

Current state: neither shields nor armor should prevent manual player damage (aka block brekaing) and only stick to blast damage, instead there's gonna be a new shield type that would have a slightly better radius to cost ratio and only prevent player damage instead. That would have a whitelist of people it trusts to place and break blocks in its AoE.

**Comment by HyperSoop** [comment]
![2023-02-28_05 43 03](https://user-images.githubusercontent.com/85982640/221749238-8bc9456f-7f65-41cd-b0cf-31fe74d52e9e.png)
have this concept "art"
they would have the same base so there isn't a need to build two just build a mixed one
then you'd be able to access the player whitelist from the interface block (dark prismarine)

Shields on ships should not span outside the ship's initial detection area for obvious reasons, we don't want people hovering over a place and making everyone below unable to break blocks lmao

I'll be in more pain trying to pick apart the tutorial issue later

**Comment by HyperSoop** [comment]
See https://gist.github.com/HyperSoop/475b00d083e2cce50235f84d2eed1320 for everything from me from now on
